### ISSUE TITLE
Add Register link to log in page.

### ISSUE THREAD

**Issue by SteveBarnett** [praekeltfoundation/vumi-go#1014]
Already have an account? Sign in:
- Email address
- Password
- Sign In

Want to register for account? Let us know at [hello@vumi.org](mailto:hello@vumi.org).

**Comment by SteveBarnett** [comment]
@badlard What info do we need / want from people to sign them up?

**Comment by badlard** [comment]
The easy ones: 
1. First name
2. Last name
3. email address.

Then I suggest we by default provide users with access to the dialogue and group message conversation types.

Now for the challenging one: what tagpool to give the user access to?

A user needs a tag (a number/address of some kind) in order to send and receive messages. We only have SMS and USSD numbers freely available for folks in SA.

For people outside of SA, we need a way to provide them with a tag. We usually use GTalk addresses, but we only have 10 of those. We've been batting around the idea of 'dynamic transports' where a user can basically set up a transport using, for e.g. their own Twitter handle and then send and receive messages over their own handle. I really like this solution (doesn't have to be Twitter).

Then, we also need to be able to set a credit cap per account. So, we'll give new users 100 free credits (currently 1 credit = $0.001 = 1 message). Once they hit 100 credits they can't send anymore. What would also be cool is a way then for a user to purchase more credits. Doing this via Praekelt's PO system is way too onerous/manual. i.e. doesn't scale.

At minimum I suggest we set up a dynamic transport to solve the tag challenge. We've been talking about Nexmo recently. Also GTalk, Twilio, SMS Sync (Android phone requirement).

For credits - I suggest we set a cap at 500 credits per month. If a user is exceeding this, then someone (an unfortunate intern?) will have to start issuing invoices...Ideally, I'd like to set up a basic payment gateway.

**Comment by SteveBarnett** [comment]
@badlard Whoa, that's a lot of stuff! :)

I think we need a scaling up plan. At the moment, it's not clear how (or if!) a person can register for Vumi. Our end goal is to have a register process that's basically automated, right?

Vague suggested iterations below.
1. Link that opens an email saying "register me," asking for details.
2. Register form that asks for name and email. Form goes to register@vumi.org, and one of us sets the account manually.
3. Register form that asks for name and email. Submission sets up account in deactivated state. One of us manually activates account.
4. Add some copy about _why_ the user should register. (Might want to move this up the list, depending on what the new personas are)

1 I can do immediately. Shall I open an issue and do so?
Should we put the rest on the roadmap?

**Comment by hodgestar** [comment]
We can do 2 simply enough with Django so I'm happy for us to immediately do
2 instead.

**Comment by badlard** [comment]
#2 sounds good. What tagpool should we point their account at?

On 20 October 2014 08:58, Simon Cross notifications@github.com wrote:

> We can do 2 simply enough with Django so I'm happy for us to immediately do
> 2 instead.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/praekelt/vumi-go/issues/1014#issuecomment-59690576.

## 

_BEN ADLARD_ | PRODUCT MANAGER
_PRAEKELTFOUNDATION_.ORG
_M_:  +27823182071  |  _S_: badlard
_T_: vumigo.tumblr.com  |  *T: *@vumiapp https://twitter.com/vumiapp
Sign up to receive Vumi's newsletter http://eepurl.com/Yb5Xn

**Comment by SteveBarnett** [comment]
Chatting with @badlard (and @hodgestar) we want to know country too. Add another field "Countries I'll be running campaigns in:"

**Comment by SteveBarnett** [comment]
Text for 4:

> Vumi is a USSD and SMS mobile messaging platform offering connectivity in Africa. Vumi serves NGOs, corporations, and entrepreneurs.

from vumi.org.

**Comment by SteveBarnett** [comment]
TODO:
- add static reg form on log in page
- add "thanks, we'll contact you soon" page
- update form to send mail to a vumi team address
