### ISSUE TITLE
Error importing contacts

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#663]
Eve just forwarded this error email she received after trying to import contacts.

I was not able to replicate this error.

Account Key: 5f2afd054a9e4bb7bfa498d29cf66b77
Group Key: 9b1b81e0dc004282bd8d0b667a8a054b
File Name: Respondents.csv
File Path: tmp/tmp-2013-08-26-f78a58a533594b1683e8bccd759f7471.upload
Fields: [(u&#39;contact&#39;, u&#39;msisdn_int&#39;), (u&#39;language&#39;, u&#39;string&#39;), (u&#39;has_opted_in&#39;, u&#39;string&#39;), (u&#39;gender&#39;, u&#39;string&#39;), (u&#39;age&#39;, u&#39;string&#39;), (u&#39;location&#39;, u&#39;string&#39;)]
Has Header: True
Exception Type:
Exception Value: None is not allowed as a value for non-null fields.
Exception Traceback:

[&#39;  File &quot;/mnt/praekelt/vumi-go/go/contacts/tasks.py&quot;, line 251, in import_contacts_file\n    contact = contact_store.new_contact(**contact_dictionary)\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/model.py&quot;, line 552, in wrapper\n    return manager.call_decorator(func)(self, _args, *_kw)\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/ve/src/vumi/vumi/utils.py&quot;, line 339, in wrapped\n    result = gen.send(result)\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/go/vumitools/contact/models.py&quot;, line 114, in new_contact\n    **self.settable_contact_fields(**fields))\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/model.py&quot;, line 680, in **call**\n    return self._modelcls(self._manager, key, **data)\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/model.py&quot;, line 201, in __init__\n    descriptor.initialize(self, field_value)\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/
 ve/src/vumi/vumi/persist/fields.py&quot;, line 37, in initialize\n    self.**set**(modelobj, value)\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/fields.py&quot;, line 85, in **set**\n    self.validate(value)\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/fields.py&quot;, line 34, in validate\n    self.field.validate(value)\n&#39;, &#39;  File &quot;/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/fields.py&quot;, line 126, in validate\n    raise ValidationError(&quot;None is not allowed as a value for non-null&quot;\n&#39;]

**Comment by smn** [comment]
She's got a row in her document where the msisdn is probably empty.

On 26 August 2013 13:03, Ben Adlard notifications@github.com wrote:

> Eve just forwarded this error email she received after trying to import
> contacts.
> 
> I was not able to replicate this error.
> 
> Account Key: 5f2afd054a9e4bb7bfa498d29cf66b77
> Group Key: 9b1b81e0dc004282bd8d0b667a8a054b
> File Name: Respondents.csv
> File Path: tmp/tmp-2013-08-26-f78a58a533594b1683e8bccd759f7471.upload
> Fields: [(u'contact', u'msisdn_int'), (u'language', u'string'),
> (u'has_opted_in', u'string'), (u'gender', u'string'), (u'age', u'string'),
> (u'location', u'string')]
> Has Header: True
> Exception Type:
> Exception Value: None is not allowed as a value for non-null fields.
> Exception Traceback:
> 
> [' File "/mnt/praekelt/vumi-go/go/contacts/tasks.py", line 251, in
> import_contacts_file\n contact =
> contact_store.new_contact(**contact_dictionary)\n', ' File
> "/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/model.py", line 552, in
> wrapper\n return manager.call_decorator(func)(self, _args, *_kw)\n', '
> File "/mnt/praekelt/vumi-go/ve/src/vumi/vumi/utils.py", line 339, in
> wrapped\n result = gen.send(result)\n', ' File
> "/mnt/praekelt/vumi-go/go/vumitools/contact/models.py", line 114, in
> new_contact\n **self.settable_contact_fields(**fields))\n', ' File
> "/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/model.py", line 680, in *
> call_\n return self._modelcls(self._manager, key, *_data)\n', ' File
> "/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/model.py", line 201, in *
> init_\n descriptor.initialize(self, field_value)\n', ' File
> "/mnt/praekelt/vumi-go/
> ve/src/vumi/vumi/persist/fields.py", line 37, in initialize\n
> self.**set**(modelobj, value)\n', ' File
> "/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/fields.py", line 85, in *
> set_\n self.validate(value)\n', ' File
> "/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/fields.py", line 34, in
> validate\n self.field.validate(value)\n', ' File
> "/mnt/praekelt/vumi-go/ve/src/vumi/vumi/persist/fields.py", line 126, in
> validate\n raise ValidationError("None is not allowed as a value for
> non-null"\n']
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/praekelt/vumi-go/issues/663
> .

## 

Simon de Haan | Chief Engineer Praekelt Foundation

praekeltfoundation.org | praekelt.com
M: +27 (0) 76 449 3806  |  http://twitter.com/smn

**Comment by hodgestar** [comment]
Let's report these errors better.

**Comment by justinvdm** [comment]
I think it would be better if we did validation and gave the user feedback in the UI on this before they complete the import 'wizard', instead of showing the errors in the email sent by the celery task. Also, as @hodgestar mentioned, it would be nice if we could display the validation on all the fields that failed validation, instead of stopping at the first validation failure.

I think once we've moved the contacts management over to the http api, we might be in a better space where we can do this validation feedback in the UI.

**Comment by justinvdm** [comment]
I think that the 'None is not allowed as a value for non-null fields' error message that was sent in the email was only sent because the user did not choose an 'msisdn' field type for the 'msisdn' field (they possibly left the field type as 'Leave as is'?).  If an msisdn field type was chosen, the error message would have shown 'Invalid MSISDN'. I think we need a way of detecting which contact fields are mandatory. That way, we could show a message like "No value found for required field 'msisdn'", even if the user chose 'Leave as is'.

The current way things are structured makes this error reporting difficult. The restructuring necessary for moving contact management to the HTTP API will hopefully involve the changes that will make this error reporting easier. Leaving this error reporting for #668 or a related issue.
