### ISSUE TITLE
Testing -- 'Packet of an unknown type received: USSDResponse'

### ISSUE THREAD

**Issue by vgeddes** [praekeltfoundation/vumi-go#719]
http://prd-sentry.za.prk-host.net/vumi/vumi-go-prod/group/62/

**Comment by hodgestar** [comment]
This should be a Vumi issue.

**Comment by hodgestar** [comment]
Probably worthwhile updating https://github.com/praekelt/vumi/issues/611 since that's closely related to this.

I think the ticket also needs to include some suggestions about what to do. We don't expected to receive USSDResponses (we expect to send them), so as far as I can tell this is clearly a bug in server Vumi connects to.

**Comment by vgeddes** [comment]
ah, hehe, I actually only opened this to test a github plugin for Sentry. Closing.
